# Generated by Django 4.0.4 on 2022-06-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', max_length=8, unique=True)),
                ('prof', models.CharField(max_length=50)),
                ('lecture_name', models.CharField(max_length=50)),
                ('positive_vote', models.IntegerField(default=0, max_length=4)),
                ('neutral_vote', models.IntegerField(default=0, max_length=4)),
                ('negative_vote', models.IntegerField(default=0, max_length=4)),
                ('multiple_vote', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
